### ISSUE TITLE
Incorrect sync from Strava (activity n -1)

### ISSUE THREAD

**Issue by tyketchum** [dblock/slack-strava#152]
When one user uploads an activity this morning, for example, Slava syncs their previous activity from two days ago instead of the activity from this morning. Any experience with this before?

**Comment by tyketchum** [comment]
That makes a lot of sense - this user did disconnect their account and reconnect it later.

This user's activities did catch up - not sure if it helped, but the user dm'd Slava with "set sync false" then again with "set sync true"

Thank you for the response!

**Comment by dblock** [comment]
Yes it did. That's actually there exactly for the workaround to use when a user reconnects a million years later and has a bagillion activities catching up (I think I added some logic to avoid that too, but I forget ;). Take a look at what happens when the user does a `set sync false` in https://github.com/dblock/slack-strava/blob/master/slack-strava/models/user.rb#L361. Their (pending) activities are deleted and the time to sync from is reset to now.
